# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Streamlabs Chatbot specifically only supports Python 2.7.13
      - image: circleci/python:2.7.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/SLCBInternationalHello

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            make install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run Tests
          command: |
            make ARGS="--junitxml=../test-reports/junit.xml" test;

      - run:
          name: Packaging Project
          command: |
            make release;

      - store_artifacts:
          path: SLCBInternationalHello.zip
          destination: release/SLCBInternationalHello.zip

      - store_artifacts:
          path: test-reports
          destination: test-reports
